package com.zotto.kds.database.m_table

import androidx.annotation.Nullable
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.google.gson.annotations.SerializedName

@Entity(tableName = "m_products")
data class MProduct(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    @SerializedName("product_id") val productId: String,
    @SerializedName("category_id") val categoryId: String,
    @SerializedName("restaurant_id") val restaurantId: Int,
    @SerializedName("date") val date: String,
    @SerializedName("status") val status: Int,
    @SerializedName("pname") val pname: String,
    @SerializedName("description") val description: String?,
    @SerializedName("cn_pname") val cnPname: String?,
    @SerializedName("cn_description") val cnDescription: String?,
    @SerializedName("picture") val picture: String?,
    @SerializedName("thumb") val thumb: String?,
    @SerializedName("type") val type: String,
    @SerializedName("price") val price: Double,
    @SerializedName("optional_modifer_id") val optionalModifierId: Int,
    @SerializedName("optional_modifier_id2") val optionalModifierId2: String?,
    @SerializedName("add_om_id") val addOmId: Int,
    @SerializedName("rem_om_id") val remOmId: Int,
    @SerializedName("forced_modifer_id") val forcedModifierId: Int,
    @SerializedName("forced_modifier_id2") val forcedModifierId2: String?,
    @SerializedName("drink_cat_id") val drinkCatId: String,
    @SerializedName("drink_id") val drinkId: String,
    @SerializedName("is_vegan") val isVegan: Int,
    @SerializedName("is_hot") val isHot: Int,
    @SerializedName("is_reduced") val isReduced: Int,
    @SerializedName("gluten_free") val glutenFree: Int,
    @SerializedName("lactose_free") val lactoseFree: Int,
    @SerializedName("nuts_free") val nutsFree: Int,
    @SerializedName("sort_order") val sortOrder: Int,
    @SerializedName("printer_id") val printerId: Int,
    @SerializedName("printer_type") val printerType: String,
    @SerializedName("printer_id2") val printerId2: String?,
    @SerializedName("printer_type2") val printerType2: String?,
    @SerializedName("points") val points: Int,
    @SerializedName("organic_content") val organicContent: Int,
    @SerializedName("online") val online: Int,
    @SerializedName("is_vat") val isVat: Int,
    @SerializedName("is_servicetax") val isServiceTax: Int,
    @SerializedName("is_localtax") val isLocalTax: Int,
    @SerializedName("is_othertax") val isOtherTax: Int,
    @SerializedName("rts_flag") val rtsFlag: Int,
    @SerializedName("scaling_qty") val scalingQty: Int,
    @SerializedName("unit_id") val unitId: Int,
    @SerializedName("happy_hours_id") val happyHoursId: String,
    @SerializedName("barcode") val barcode: String?,
    @SerializedName("preparation_time") val preparationTime: String,
    @SerializedName("min_qty") val minQty: Int,
    @SerializedName("date_modified") val dateModified: String,
    @SerializedName("print_products_flag") val printProductsFlag: Int,
    @SerializedName("print_sequence") val printSequence: Int,
    @SerializedName("is_stamp") val isStamp: Int,
    @SerializedName("stamp_count") val stampCount: Int,
    @SerializedName("expiry_time") val expiryTime: String,
    @SerializedName("expiry_type") val expiryType: String,
    @SerializedName("remote_product_id") val remoteProductId: String?,
    @SerializedName("inshop_ordering") val inshopOrdering: Int,
    @SerializedName("detour_ids") val detourIds: String?,
    @SerializedName("open_dish") val openDish: Int,
    @SerializedName("is_deal") val isDeal: Int,
    @SerializedName("is_deleted") val isDeleted: Int,
    @SerializedName("chain_owner_id") val chainOwnerId: Int,
    @SerializedName("restaurant_group_id") val restaurantGroupId: Int,
    @SerializedName("sku") val sku: String?,
    @SerializedName("device_id") val deviceId: Int,
    @SerializedName("pour_device_id") val pourDeviceId: String?,
    @SerializedName("is_deposit") val isDeposit: Int,
    @SerializedName("deposit_price") val depositPrice: Double,
    @SerializedName("is_pour") val isPour: Int,
    @SerializedName("linked_modifiers") val linkedModifiers: String?,
    @SerializedName("is_linked_product") val isLinkedProduct: Int,
    @SerializedName("energy_content") val energyContent: String?,
    @SerializedName("food_category") val foodCategory: String?,
    @SerializedName("is_spicy") val isSpicy: Int,
    @SerializedName("is_self_order_enable") val isSelfOrderEnable: Int,
    @SerializedName("is_vegetarian") val isVegetarian: Int,
    @SerializedName("menu_type") val menuType: String,
    @SerializedName("cloud_image_url") val cloudImageUrl: String?,
    @SerializedName("stockStatus") val stockStatus: Int
)
